# Generated by Django 5.0.2 on 2024-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=122)),
                ('reporter_email', models.CharField(max_length=122)),
                ('criminal_desc', models.TextField()),
                ('phone', models.CharField(max_length=122)),
                ('date_of_report', models.DateField()),
            ],
        ),
    ]
