# Generated by Django 5.0.2 on 2024-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=122)),
                ('uname', models.CharField(max_length=122)),
                ('phone_no', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('pass1', models.CharField(max_length=122)),
                ('pass2', models.CharField(max_length=122)),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='criminal_desc',
            new_name='crime_desc',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='email',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
    ]
