# Generated by Django 5.0.2 on 2024-04-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registerpage_rename_criminal_desc_report_crime_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterPage',
        ),
        migrations.DeleteModel(
            name='Userlogin',
        ),
    ]
