# Generated by Django 5.0.2 on 2024-04-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_registerpage_delete_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('crime_type', models.CharField(max_length=100)),
                ('criminal_age', models.IntegerField()),
                ('crime_mob_no', models.IntegerField()),
                ('date_of_crime', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('crime_spot', models.TextField()),
                ('clue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YourDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('date', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
