# Generated by Django 5.0.2 on 2024-04-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_crimedetails_yourdetails_delete_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrimeDetails',
            new_name='CrimeDetail',
        ),
        migrations.RenameModel(
            old_name='YourDetails',
            new_name='YourDetail',
        ),
    ]
