# Generated by Django 5.0.2 on 2024-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_crimedetails_crimedetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedetail',
            name='case_id',
            field=models.IntegerField(default=452631),
            preserve_default=False,
        ),
    ]
