# Generated by Django 5.0.2 on 2024-04-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_crimedetail_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedetail',
            name='cs_status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crimedetail',
            name='case_id',
            field=models.CharField(default=123456, max_length=10, unique=True),
        ),
    ]
