# Generated by Django 5.0.2 on 2024-04-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_crimedetail_user_yourdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimedetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yourdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='yourdetail',
            name='user_id',
            field=models.CharField(default=100000, max_length=10, unique=True),
        ),
    ]
