# Generated by Django 5.0.2 on 2024-07-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_yourdetail_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimedetail',
            options={'permissions': (('can_create_crime_report', 'Can create crime report'), ('can_update_crime_report', 'Can update crime report'), ('can_delete_crime_report', 'Can delete crime report'))},
        ),
    ]
